CREATE TABLE players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    display_name VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255),
    auth_provider VARCHAR(50) NOT NULL,
    level INT NOT NULL,
    experience BIGINT NOT NULL,
    coins BIGINT NOT NULL,
    energy INT NOT NULL,
    last_daily_claim_at TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE active_boosts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    multiplier DOUBLE PRECISION NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_boost_player FOREIGN KEY (player_id) REFERENCES players(id)
);

INSERT INTO players (email, display_name, password_hash, auth_provider, level, experience, coins, energy, created_at, updated_at)
VALUES ('demo@game.local', 'DemoPlayer', '$2a$10$4QxBqg0x5H.Kq8XNYQXWxe9f/68kYjgm2iUZfM7WmfLw4f8gFvF8S', 'LOCAL', 1, 0, 100, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
