CREATE TABLE players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    display_name VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255),
    auth_provider VARCHAR(50) NOT NULL,
    level INT NOT NULL,
    experience BIGINT NOT NULL,
    coins BIGINT NOT NULL,
    energy INT NOT NULL,
    last_daily_claim_at TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE active_boosts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    multiplier DOUBLE PRECISION NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_boost_player FOREIGN KEY (player_id) REFERENCES players(id)
);
