spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/idlegame}
    username: ${DB_USERNAME:idlegame}
    password: ${DB_PASSWORD:idlegame}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: false
  liquibase:
    contexts: ${LIQUIBASE_CONTEXTS:prod}
