spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/idlegame
    username: idlegame
    password: idlegame
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: false
